name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  macOS:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: Resolve Packages
      run: swift package resolve
    - name: Compile Source
      run: swift build -v
    - name: Run Tests
      run: swift test -v
  
  ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Resolve Packages
      run: swift package resolve
    - name: Compile Source
      run: swift build -v
    - name: Run Tests
      run: swift test -v
