name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  Swift-Package:
    strategy:
      matrix:
        os: [macos-15, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Resolve Packages
      run: swift package resolve

    - name: Compile Source
      run: swift build

    - name: Run Tests
      run: swift test
